### ISSUE TITLE
Access properties in Javascript

### ISSUE THREAD

**Issue by GabrielGil** [fknussel/webpack-version-file#1]
Hey! 

Thank you for this great plugin!

I am using it with Angular, and I was wondering of there is a way of accessing this variables that you use on the templates directly on the javascript, so the app can show the build version the browser is running.

If I fetch the end file generated, there are some chances of the bundle file being outdated, but fetching a more recent version code.

Gabriel

**Comment by fed** [comment]
Hey! First issue :tada:

You could definitely try to read the file and parse its content, although depending on what data you need there might be an easier way out.

If all you need is the package name and version number, you can just fetch those values from your `package.json`, something in the lines of:

```js
import {name, version} from './path/to/your/package.json';
```

or, if you are not using ES6:

```js
var pkg = require('./path/to/your/package.json');
var name = pkg.name;
var version = pkg.version;
```

Either way, now you've got both a `name` and `version` variables readily available for you to use wherever you need. The key here is that you can use `require` or `import` to load json files through [a json loader](https://github.com/webpack/json-loader).

The `buildDate`, however, is generated on runtime -- that is, when the plugin runs, and cannot be retrieved from your `package.json` file. In this case you might need to read and parse the outputted `version.txt` file.

What I'd suggest is tweaking the plugin settings to output a `version.json` file holding valid JSON data. This will make it easier for you to import this file and get the data you need.

```js
new VersionFile({
      output: './build/version.json',
      templateString: '{\n' +
        '\t"name": "<%= name %>",\n' +
        '\t"version": "<%= version %>",\n' +
        '\t"buildDate": "<%= buildDate %>",\n' +
        '\t"environment": "<%= environment %>"\n' +
        '}',
      data: {
        environment: process.env.NODE_ENV || 'development'
      }
})
```

You might want to avoid doing this inline though, go ahead and create a `version.ejs` template file instead.

Yell out if you happen to need more help 🙂  Good to know you found this plugin useful!

**Comment by GabrielGil** [comment]
Hey, it was a pleasure to be the first one. haha

Thank you for the explanation, it is really helpful. And yes, I am also using ES6 🙏 

I was actually pleased with your plugin because maybe I could use template tags somehow to retrieve the build date as a string to use in javascript. I will set it up like that for now.

Thank you again for your help. :)
